from src.core.util.resource import Image, Spritesheet, Sound, Font, RoomData

def define_resources() -> None:
    Spritesheet("player_idle_back", "player/idle_back.png", 2)
    Spritesheet("player_idle_front", "player/idle_front.png", 2)
    Spritesheet("player_idle_side", "player/idle_side.png", 2)
    Spritesheet("player_walk_back", "player/walk_back.png", 4)
    Spritesheet("player_walk_front", "player/walk_front.png", 4)
    Spritesheet("player_walk_side", "player/walk_side.png", 4)
    Spritesheet("player_walk_hold_front", "player/walk_hold_front.png", 4)
    Spritesheet("player_walk_hold_back", "player/walk_hold_back.png", 4)
    Spritesheet("player_walk_hold_side", "player/walk_hold_side.png", 4)
    Spritesheet("player_sleeping", "player/sleeping.png", 4)
    Spritesheet("player_phone", "player/phone_call.png", 2)

    Image("vacuum_world", "items/vacuum_world.png")
    Image("vacuum_front", "items/vacuum_front.png")
    Image("vacuum_side", "items/vacuum_side.png")
    Image("plate", "items/plate.png")
    Image("chicken", "items/chicken_frosted.png")

    Image("stack_of_plates_5", "rooms/living_room/stack_of_plates_5.png")
    Image("stack_of_plates_4", "rooms/living_room/stack_of_plates_4.png")
    Image("stack_of_plates_3", "rooms/living_room/stack_of_plates_3.png")
    Image("stack_of_plates_2", "rooms/living_room/stack_of_plates_2.png")
    Image("stack_of_plates_1", "rooms/living_room/stack_of_plates_1.png")
    Image("fridge_opened", "rooms/living_room/fridge_opened.png")
    Image("fridge_closed", "rooms/living_room/fridge.png")
    Image("microwave_opened", "rooms/living_room/microwave_opened.png")
    Image("microwave_closed", "rooms/living_room/microwave.png")
    Spritesheet("bathtub_shallow", "bathtub_shallow.png", 3)
    Spritesheet("bathtub_medium", "bathtub_medium.png", 3)
    Spritesheet("bathtub_full", "bathtub_full.png", 3)
    Image("bathtub", "rooms/bathroom/bathtub.png")
    Image("bathtub_shallow", "bathtub_shallow_still.png")
    Image("bathtub_medium", "bathtub_medium_still.png")
    Image("bathtub_full", "bathtub_full_still.png")

    Image("hamster_side", "items/hamster_side.png")
    Image("hamster_standing", "items/hamster_standing.png")

    Spritesheet("surprise", "surprise.png", 8)
    Image("clipboard_icon", "clipboard_icon_letter.png")
    Image("clipboard", "clipboard_large_lined.png")
    Image("thermometer", "thermometer.png")
    Image("bathtub_handle_base", "bathtub_handle_base.png")
    Image("thermometer_icons", "thermometer_icons.png")
    Image("bathtub_indicator", "bathtub_indicator.png")

    RoomData("living_room", "living_room.json")
    RoomData("bedroom", "bedroom.json")
    RoomData("bathroom", "bathroom.json")

    Spritesheet("title_text_scroll", "text_scroll.png", 15)
    Image("button_large", "button_large.png")
    Image("button_medium", "button_medium.png")
    Image("button_small", "button_small.png")
    Image("titlescreen_bg", "titlescreen_bg.png")
    Spritesheet("call_animation_mom", "call_animation_mom.png", 8, scale=2)
    Image("ending_background", "ending_background.png")
    Image("ending_border", "ending_border.png")
    Image("ending_characters_1", "ending_characters_1.png")
    Image("ending_characters_2", "ending_characters_2.png")
    Image("ending_characters_3", "ending_characters_3.png")

    Image("speech_bubble_corner", "speech_bubble_corner.png")
    Image("speech_bubble_side", "speech_bubble_side.png")
    Image("key_hint_e", "key_hint_e.png")
    Image("door_icon", "door_icon.png")
    Spritesheet("mom_slider", "mom_slider_bar.png", 8)
    Image("mom_slider_knob", "mom_slider_icon.png")

    Sound("ringtone", "ringtone.ogg")
    for i in range(1, 9):
        Sound(f"voice_1_{i}", f"voice_1_{i}.ogg")
    for i in range(1, 9):
        Sound(f"voice_2_{i}", f"voice_2_{i}.ogg")
    Sound("microwave", "microwave_loud.ogg")
    Sound("fridge_open", "fridge_open.ogg")
    Sound("fridge_close", "fridge_close.ogg")
    Sound("microwave_open", "microwave_open.ogg", 0.45)
    Sound("microwave_close", "microwave_close.ogg", 0.65)
    Sound("microwave_open_title", "microwave_open.ogg")
    Sound("beep", "beep.ogg")
    Sound("knock", "knock.ogg")
    Sound("water", "water.ogg")
